PKGDIR		?= ../..
L4DIR		?= $(PKGDIR)/../..

TARGET           = ipc_bench
SRC_CC           = ipc_bench.cc
REQUIRES_LIBS    = libpthread
DEPENDS_PKGS     = $(REQUIRES_LIBS)

include $(L4DIR)/mk/prog.mk
